import LoginHistory from "./LoginHistory";

function ProfileView({
  user,
  editName,
  onEditNameChange,
  onUpdateProfile,
  isSettingUp2FA,
  qrCodeUrl,
  twoFactorSecret,
  twoFactorSetupCode,
  onSetupCodeChange,
  onSetup2FA,
  onEnable2FA,
  onDisable2FA,
  onCancelSetup,
  loginHistory,
  
}) {
  return (
    <div className="profile-view-container">
      <h2>Account Settings</h2>
      <p className="profile-info-text">
        <strong>Email Address:</strong> {user.email}
      </p>
      <p className="profile-info-text">
        <strong>System ID Key:</strong> {user.id}
      </p>
      <p className="profile-info-text">
        <strong>Assigned Role:</strong> {user.role || "user"}
      </p>
      <p className="profile-info-text">
        <strong>Two-Factor Status: </strong>
        <span
          style={{
            fontWeight: "bold",
            color: user.isTwoFactorEnabled ? "#22c55e" : "#ef4444",
          }}
        >
          {user?.isTwoFactorEnabled ? "Active" : "Disabled"}
        </span>
      </p>
      <hr style={{ border: "0.5px solid #eee", margin: "15px 0" }} />

      <form onSubmit={onUpdateProfile} className="form-layout">
        <h3>Update Display Name</h3>
        <input
          type="text"
          className="input-field"
          value={editName}
          onChange={(e) => onEditNameChange(e.target.value)}
          required
          placeholder="Enter new name"
        />
        <button type="submit" className="btn btn-success">
          Save Changes
        </button>
      </form>

      <hr style={{ border: "0.5px solid #eee", margin: "25px 0" }} />

      <div style={{ marginTop: "20px" }}>
        <LoginHistory loginHistory={loginHistory || []} />
      </div>

      <hr style={{ border: "0.5px solid #eee", margin: "25px 0" }} />

      <div
        className="two-factor-management-section"
        style={{ textAlign: "left" }}
      >
        <h3>Two-Factor Authentication</h3>

        {!user.isTwoFactorEnabled && !isSettingUp2FA && (
          <div>
            <p style={{ fontSize: "14px", color: "#666" }}>
              Protect your Profile using Google Two-Factor Authentication.
            </p>
            <button onClick={onSetup2FA} className="btn btn-primary">
              Enable Two-Factor Authentication
            </button>
          </div>
        )}

        {user.isTwoFactorEnabled && (
          <div>
            <p style={{ fontSize: "14px", color: "#666" }}>
              Your profile is actively secured using time-based verification
              protocols.
            </p>
            <button onClick={onDisable2FA} className="btn btn-danger">
              Disable Two-Factor Authentication
            </button>
          </div>
        )}

        {isSettingUp2FA && (
          <div
            style={{
              backgroundColor: "#f8fafc",
              padding: "15px",
              borderRadius: "8px",
              border: "1px solid #e2e8f0",
              marginTop: "15px",
            }}
          >
            <h4>1. Scan this QR Code with your Authenticator Application</h4>
            {qrCodeUrl && (
              <img
                src={qrCodeUrl}
                alt="2FA Setup QR Code"
                style={{
                  display: "block",
                  margin: "15px 0",
                  maxWidth: "200px",
                }}
              />
            )}
            <p style={{ fontSize: "13px", color: "#475569" }}>
              <strong>Manual Secret Key Setup:</strong>{" "}
              <code>{twoFactorSecret}</code>
            </p>

            <form
              onSubmit={onEnable2FA}
              className="form-layout"
              style={{ marginTop: "20px" }}
            >
              <h4>2. Enter the Verification Code generated by the app:</h4>
              <input
                type="text"
                className="input-field"
                placeholder="6-Digit Code"
                maxLength={6}
                value={twoFactorSetupCode}
                onChange={(e) => onSetupCodeChange(e.target.value)}
                required
              />
              <div style={{ display: "flex", gap: "10px" }}>
                <button type="submit" className="btn btn-success">
                  Verify & Complete Setup
                </button>
                <button
                  type="button"
                  onClick={onCancelSetup}
                  className="btn btn-muted"
                >
                  Cancel Setup
                </button>
              </div>
            </form>
          </div>
        )}
      </div>
    </div>
  );
}

export default ProfileView;
